<template>
  <form
    data-netlify="true"
    name="contact"
    method="POST"
  >
    <input
      name="Anrede"
      value="Frau"
      type="radio"
    />
    <input
      name="Anrede"
      value="Herr"
      type="radio"
    />
    <input
      name="Anrede"
      value="Divers"
      type="radio"
    />
    <input
      name="Vorname"
      value=""
      type="text"
    />
    <input
      name="Nachname"
      value=""
      type="text"
    />
    <input
      name="E-Mail"
      value=""
      type="email"
    />
    <input
      name="Telefonnummer"
      value=""
      type="text"
    />
    <textarea name="Nachricht"></textarea>
    <input
      name="Rückruf"
      type="checkbox"
    />
    <input
      name="Datenschutzerklärung"
      type="checkbox"
    />
    <button type="submit">Nachricht abschicken</button>
  </form>
</template>

<script setup>
definePageMeta({
  layout: false,
});
</script>
